import { Document } from 'mongoose';
import { Question } from '../category/category.model';

export interface Room extends Document {
  roomCode: string; // Room code generated by the frontend
  users: { username: string }[]; // List of users in the room
  quizCategories: string[]; // Array of selected quiz category names
  questions: Question[]; // Questions gathered from the categories
  timer: number; // Timer for the room
  createdAt: Date; // Room creation timestamp
  qrCode: string; // Base64-encoded QR code for the room
}
